from src.application.schemas.base import CamelCaseModel, SnakeCaseModel
from src.application.schemas.request import (
    AuthRequest,
    ScanCheckData,
    ScanCheckRequest,
    TicketListQuery,
    TicketSearchRequest,
    TicketSearchByMailRequest,
)
from src.application.schemas.response import (
    SuccessResponse,
    ErrorResponse,
    HealthResponse,
    UserResponse,
    AuthResponse,
    EventListItem,
    EventListResponse,
    ScanCountsResponse,
    CheckResultResponse,
    TicketListItem,
    TicketListResponse,
    TicketResponse,
    StatisticResponse,
)
from src.application.schemas.dto import (
    UserDTO,
    PermissionDTO,
    EventDTO,
    SessionDTO,
    TicketDTO,
    TicketListItemDTO,
    ScanCheckDTO,
    ScanCountsDTO,
    StatisticDTO,
)

__all__ = [
    "CamelCaseModel",
    "SnakeCaseModel",
    # Request
    "AuthRequest",
    "ScanCheckData",
    "ScanCheckRequest",
    "TicketListQuery",
    "TicketSearchRequest",
    "TicketSearchByMailRequest",
    # Response
    "SuccessResponse",
    "ErrorResponse",
    "HealthResponse",
    "UserResponse",
    "AuthResponse",
    "EventListItem",
    "EventListResponse",
    "ScanCountsResponse",
    "CheckResultResponse",
    "TicketListItem",
    "TicketListResponse",
    "TicketResponse",
    "StatisticResponse",
    # DTO
    "UserDTO",
    "PermissionDTO",
    "EventDTO",
    "SessionDTO",
    "TicketDTO",
    "TicketListItemDTO",
    "ScanCheckDTO",
    "ScanCountsDTO",
    "StatisticDTO",
]
